#!/bin/sh
set -eu

target=${TARGET:-mipsel-linux-4.x-musl}
artifact=${ARTIFACT:-dist/busierbox-$target}

if [ "${SKIP_BUILD:-0}" != "1" ]; then
    TARGET="$target" make package
fi

tests/integration/glinet/push-and-test "$artifact"
