"""Line REPL navigation command callback adapters."""

from gritlib.line_navigation_commands import dispatch_line_navigation_command


def build_line_navigation_dispatch_callback(
    cfg,
    *,
    target_filter_func,
    module_func,
    append_event_fn,
    clear_results_func,
    set_context_func,
    print_listeners_func,
    select_listener_func,
    print_targets_func,
    select_target_func,
    print_sessions_func,
    clear_sessions_func,
    session_help_func,
    select_session_func,
    interact_session_func,
    print_routes_func,
    add_route_func,
    start_route_func,
    stop_route_func,
    delete_route_func,
    route_help_func,
    select_route_func,
    number_func,
    select_job_func,
    select_action_func,
    clear_console_context_func,
    back_func,
    start_service_func,
    stop_service_func,
    start_job_func,
    cancel_job_func,
    run_action_func,
    interact_target_func,
):
    def record_alias(alias, canonical):
        append_event_fn(
            cfg,
            "workbench",
            "workbench_console_alias_used",
            details={
                "alias": str(alias or ""),
                "canonical": str(canonical or ""),
            },
        )

    def dispatch_navigation(command, args):
        return dispatch_line_navigation_command(
            command,
            args,
            target_selected=bool(target_filter_func(cfg)),
            module=module_func(cfg),
            record_alias_func=record_alias,
            clear_results_func=lambda: clear_results_func(cfg),
            set_listeners_context_func=lambda: set_context_func(cfg, "listeners"),
            print_listeners_func=print_listeners_func,
            select_listener_func=select_listener_func,
            set_targets_context_func=lambda: set_context_func(cfg, "targets"),
            print_targets_func=print_targets_func,
            select_target_func=select_target_func,
            set_sessions_context_func=lambda: set_context_func(cfg, "sessions"),
            print_sessions_func=print_sessions_func,
            clear_sessions_func=clear_sessions_func,
            session_help_func=session_help_func,
            select_session_func=select_session_func,
            interact_session_func=interact_session_func,
            set_routes_context_func=lambda: set_context_func(cfg, "routes"),
            print_routes_func=print_routes_func,
            add_route_func=add_route_func,
            start_route_func=start_route_func,
            stop_route_func=stop_route_func,
            delete_route_func=delete_route_func,
            route_help_func=route_help_func,
            select_route_func=select_route_func,
            number_func=number_func,
            select_job_func=select_job_func,
            select_action_func=select_action_func,
            clear_target_func=lambda: select_target_func("all", targets=[]),
            root_func=lambda quiet=False: clear_console_context_func(cfg, quiet=quiet),
            back_func=lambda: back_func(cfg),
            start_service_func=start_service_func,
            stop_service_func=stop_service_func,
            start_job_func=start_job_func,
            cancel_job_func=cancel_job_func,
            run_action_func=run_action_func,
            interact_target_func=interact_target_func,
        )

    return dispatch_navigation
