"""Line REPL core command callback adapters."""

from gritlib.line_core_commands import dispatch_line_core_command
from gritlib.line_workspace import line_repl_status_bar


def build_line_core_dispatch_callback(
    cfg,
    *,
    default_config,
    load_config_func,
    defaults,
    workbench_snapshot_func,
    clear_module_context_func,
    print_workspace_snapshot_func,
    reload_config_func,
    clear_console_context_func,
    info_func,
    next_func,
    options_func,
    set_context_func,
    build_run_func,
    set_global_option_func,
    set_context_option_func,
    unset_global_option_func,
    unset_context_option_func,
    rename_target_func,
    note_target_func,
    alias_target_func,
    local_ips_func,
    probe_results_func,
    probe_config_func,
    probe_clear_func,
    probe_serve_func,
    probe_delivery_func,
    probe_paste_func,
    probe_script_func,
    help_func,
    probe_start_func,
    survey_results_func,
    survey_config_func,
    survey_preset_func,
    append_event_fn,
    print_func=print,
):
    def dispatch_core(command, args):
        return dispatch_line_core_command(
            command,
            args,
            status_func=lambda: print_func(line_repl_status_bar(workbench_snapshot_func(cfg))),
            ips_func=lambda: local_ips_func(workbench_snapshot_func(cfg)),
            workspace_func=lambda: (
                clear_module_context_func(cfg, quiet=True),
                print_workspace_snapshot_func(workbench_snapshot_func(cfg)),
            ),
            reload_func=lambda: reload_config_func(
                cfg,
                default_config=default_config,
                load_config_fn=load_config_func,
                defaults=defaults,
                append_event_fn=append_event_fn,
            ),
            root_func=lambda quiet=False: clear_console_context_func(cfg, quiet=quiet),
            info_func=info_func,
            next_func=next_func,
            options_func=options_func,
            set_context_func=set_context_func,
            build_run_func=lambda build_args: build_run_func(cfg, build_args),
            set_global_option_func=lambda key, value: set_global_option_func(cfg, key, value),
            set_context_option_func=lambda key, value: set_context_option_func(cfg, key, value),
            unset_global_option_func=lambda key: unset_global_option_func(cfg, key),
            unset_context_option_func=unset_context_option_func,
            rename_target_func=lambda value: rename_target_func(cfg, value),
            note_target_func=lambda value: note_target_func(cfg, value),
            alias_target_func=lambda value: alias_target_func(cfg, value),
            probe_results_func=lambda: probe_results_func(cfg, append_event_fn=append_event_fn),
            probe_config_func=lambda probe_args: probe_config_func(
                cfg,
                probe_args,
                append_event_fn=append_event_fn,
            ),
            probe_clear_func=lambda probe_args: probe_clear_func(
                cfg,
                probe_args,
                append_event_fn=append_event_fn,
            ),
            probe_serve_func=lambda probe_args: probe_serve_func(
                cfg,
                probe_args,
                append_event_fn=append_event_fn,
            ),
            probe_delivery_func=lambda: probe_delivery_func(cfg),
            probe_paste_func=lambda base64_mode=False: probe_paste_func(
                cfg,
                paste=True,
                base64_mode=base64_mode,
            ),
            probe_script_func=lambda: probe_script_func(cfg, paste=False),
            help_func=help_func,
            probe_start_func=probe_start_func,
            survey_results_func=lambda: survey_results_func(cfg, append_event_fn=append_event_fn),
            survey_config_func=lambda survey_args: survey_config_func(
                cfg,
                survey_args,
                append_event_fn=append_event_fn,
            ),
            survey_preset_func=lambda survey_args: survey_preset_func(
                cfg,
                survey_args,
                append_event_fn=append_event_fn,
            ),
        )

    return dispatch_core
