#!/bin/sh
set -eu

file=${1:-dist/grit}

python3 - "$file" <<'PY'
import sys

path = sys.argv[1]
with open(path, "rb") as fh:
    fh.seek(0, 2)
    size = fh.tell()
    if size < 512:
        print("payload_present=no")
        raise SystemExit(0)
    fh.seek(size - 512)
    trailer = fh.read(512).split(b"\0", 1)[0].decode("ascii", "replace")

if not trailer.startswith("BBXPAYLOADv1\n"):
    print("payload_present=no")
    raise SystemExit(0)
print("payload_present=yes")
for line in trailer.splitlines()[1:]:
    if line == "END":
        break
    print(line)
PY

