set -g history-limit 10000
set -g mouse off
set -g status on
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display-message "reloaded"
