#!/usr/bin/env python3
"""Shared matrix helpers for BusierBox build and mirror tooling."""

import csv
import json
import os
import pathlib
import shlex
import subprocess


ROOT = pathlib.Path(__file__).resolve().parents[1]
PAYLOAD_PRESETS = ROOT / "presets" / "payload"


def csv_items(value):
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def shell_quote(value):
    return shlex.quote(str(value))


def list_targets():
    proc = subprocess.run(
        [str(ROOT / "scripts" / "resolve-target"), "--list"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        check=True,
    )
    targets = []
    for row in csv.reader(proc.stdout.splitlines(), delimiter="\t"):
        if len(row) >= 2 and row[1] == "supported":
            targets.append(row[0])
    return targets


def list_payloads():
    return sorted(path.stem for path in PAYLOAD_PRESETS.glob("*.conf"))


def load_matrix(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def expand_jobs(args):
    matrix = load_matrix(args.matrix) if getattr(args, "matrix", None) else {}
    targets = csv_items(getattr(args, "targets", None)) or matrix.get("targets") or ["native"]
    payloads = (
        csv_items(getattr(args, "payload_presets", None))
        or csv_items(getattr(args, "payloads", None))
        or matrix.get("payload_presets")
        or matrix.get("payloads")
        or ["default"]
    )
    formats = csv_items(getattr(args, "formats", None)) or matrix.get("formats") or ["tgz"]
    if targets == ["all"]:
        targets = list_targets()
    if payloads == ["all"]:
        payloads = list_payloads()

    jobs = []
    for target in targets:
        for payload in payloads:
            for fmt in formats:
                jobs.append({
                    "name": f"{target}-{payload}-{fmt}",
                    "target": target,
                    "payload": payload,
                    "format": fmt,
                    "variant": {},
                })

    variants = matrix.get("variants") or {}
    for name, data in sorted(variants.items()):
        v_targets = data.get("targets") or ([data.get("target")] if data.get("target") else targets)
        v_payloads = data.get("payload_presets") or data.get("payloads") or ([data.get("payload_preset") or data.get("payload")] if (data.get("payload_preset") or data.get("payload")) else payloads)
        v_formats = data.get("formats") or ([data.get("format")] if data.get("format") else formats)
        for target in v_targets:
            for payload in v_payloads:
                for fmt in v_formats:
                    jobs.append({
                        "name": name,
                        "target": target,
                        "payload": payload,
                        "format": fmt,
                        "variant": data,
                    })
    return jobs


def write_config(path, target, payload, fmt, variant=None):
    preset = PAYLOAD_PRESETS / f"{payload}.conf"
    if not preset.exists():
        raise SystemExit(f"build matrix: missing payload preset {payload}")
    text = preset.read_text(encoding="utf-8")
    variant = variant or {}
    lines = [
        text.rstrip(),
        "",
        "# generated by BusierBox matrix tooling",
        f"BB_TARGET_PRESET={shell_quote(target)}",
        f"BB_PAYLOAD_PRESET={shell_quote(payload)}",
        f"PAYLOAD_FORMAT={shell_quote(fmt)}",
    ]
    for key, value in sorted(variant.items()):
        if key in {"target", "targets", "payload", "payloads", "payload_preset", "payload_presets", "format", "formats"}:
            continue
        if isinstance(value, bool):
            value = "yes" if value else "no"
        lines.append(f"{key}={shell_quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_shell_assignments(text):
    values = {}
    for line in text.splitlines():
        if "=" not in line or line.lstrip().startswith("#"):
            continue
        key, raw = line.split("=", 1)
        key = key.strip()
        try:
            parsed = shlex.split(raw, posix=True)
            values[key] = parsed[0] if parsed else ""
        except ValueError:
            values[key] = raw.strip().strip('"')
    return values


def resolve_target(requested_target, config=None):
    env = os.environ.copy()
    if config is not None:
        env["BUSIERBOX_CONFIG"] = str(config)
    proc = subprocess.run(
        [str(ROOT / "scripts" / "resolve-target"), requested_target],
        cwd=ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or f"resolve-target failed for {requested_target}")
    return parse_shell_assignments(proc.stdout)


def matrix_identity(args):
    return {
        "matrix": getattr(args, "matrix", None),
        "targets": getattr(args, "targets", None),
        "payloads": getattr(args, "payloads", None),
        "payload_presets": getattr(args, "payload_presets", None),
        "formats": getattr(args, "formats", None),
    }
