#!/usr/bin/env python3
"""Compatibility wrapper for grit-console artifact commands."""

import sys

from gritlib.console_artifact import handle_artifact_command


def main():
    return handle_artifact_command(sys.argv[1:], program="grit-artifact")


if __name__ == "__main__":
    raise SystemExit(main())
