#ifndef GRIT_EFFECTIVE_CONFIG_H
#define GRIT_EFFECTIVE_CONFIG_H

#include "runtime_config.h"

#ifndef GRIT_RUNTIME_MODE
#define GRIT_RUNTIME_MODE "extract"
#endif
#ifndef GRIT_NORESIDUE_LEVEL
#define GRIT_NORESIDUE_LEVEL "best-effort"
#endif
#ifndef GRIT_RUNTIME_ROOT
#define GRIT_RUNTIME_ROOT "./.grit"
#endif
#ifndef GRIT_RUNTIME_ALLOW_FALLBACK_ROOT
#define GRIT_RUNTIME_ALLOW_FALLBACK_ROOT "no"
#endif
#ifndef GRIT_RUNTIME_FALLBACK_ROOT
#define GRIT_RUNTIME_FALLBACK_ROOT "/tmp/.grit"
#endif
#ifndef GRIT_ZERO_ARG_MODE
#define GRIT_ZERO_ARG_MODE "help"
#endif
#ifndef GRIT_ZERO_ARG_LOG_MODE
#define GRIT_ZERO_ARG_LOG_MODE "quiet"
#endif
#ifndef GRIT_ZERO_ARG_CUSTOM_COMMAND
#define GRIT_ZERO_ARG_CUSTOM_COMMAND ""
#endif
#ifndef GRIT_RSHELL_MODE
#define GRIT_RSHELL_MODE "ssh"
#endif
#ifndef GRIT_RSHELL_TRANSPORT
#define GRIT_RSHELL_TRANSPORT GRIT_RSHELL_MODE
#endif
#ifndef GRIT_RSHELL_ENCRYPTION
#define GRIT_RSHELL_ENCRYPTION "tls"
#endif
#ifndef GRIT_RSHELL_ALLOW_PLAINTEXT
#define GRIT_RSHELL_ALLOW_PLAINTEXT "no"
#endif
#ifndef GRIT_RSHELL_AUTHKEYS_MODE
#define GRIT_RSHELL_AUTHKEYS_MODE "disabled"
#endif
#ifndef GRIT_RSHELL_RUN_MODE
#define GRIT_RSHELL_RUN_MODE "auto"
#endif
#ifndef GRIT_RSHELL_SESSION_POLICY
#define GRIT_RSHELL_SESSION_POLICY "single"
#endif
#ifndef GRIT_RSHELL_GENERATE_HOSTKEY_IF_MISSING
#define GRIT_RSHELL_GENERATE_HOSTKEY_IF_MISSING "no"
#endif
#ifndef GRIT_RSHELL_SOCAT_PORT
#define GRIT_RSHELL_SOCAT_PORT "22203"
#endif
#ifndef GRIT_RSHELL_SHELL_PROVIDER
#define GRIT_RSHELL_SHELL_PROVIDER "auto"
#endif
#ifndef GRIT_RSHELL_CUSTOM_SHELL
#define GRIT_RSHELL_CUSTOM_SHELL ""
#endif
#ifndef GRIT_RSHELL_RETRY_COUNT
#define GRIT_RSHELL_RETRY_COUNT "1"
#endif
#ifndef GRIT_RSHELL_RETRY_INTERVAL_SEC
#define GRIT_RSHELL_RETRY_INTERVAL_SEC "5"
#endif
#ifndef GRIT_RSHELL_RETRY_JITTER_PCT
#define GRIT_RSHELL_RETRY_JITTER_PCT "20"
#endif
#ifndef GRIT_RSHELL_RETRY_BACKOFF
#define GRIT_RSHELL_RETRY_BACKOFF "none"
#endif
#ifndef GRIT_RSHELL_RETRY_MAX_INTERVAL_SEC
#define GRIT_RSHELL_RETRY_MAX_INTERVAL_SEC "300"
#endif
#ifndef GRIT_AUTORUN_GUARD_ENABLE
#define GRIT_AUTORUN_GUARD_ENABLE "yes"
#endif
#ifndef GRIT_AUTORUN_GUARD_PATH
#define GRIT_AUTORUN_GUARD_PATH GRIT_RUNTIME_ROOT "/run"
#endif
#ifndef GRIT_AUTORUN_REENTRY_ACTION
#define GRIT_AUTORUN_REENTRY_ACTION "status"
#endif
#ifndef GRIT_AUTORUN_STALE_LOCK_POLICY
#define GRIT_AUTORUN_STALE_LOCK_POLICY "recover"
#endif
#ifndef GRIT_OPERATOR_REMOTE_FORWARD_PORT
#define GRIT_OPERATOR_REMOTE_FORWARD_PORT "2200"
#endif
#ifndef GRIT_OPERATOR_SERVER_HOST
#define GRIT_OPERATOR_SERVER_HOST ""
#endif
#ifndef GRIT_OPERATOR_SERVER_USER
#define GRIT_OPERATOR_SERVER_USER "operator"
#endif
#ifndef GRIT_OPERATOR_SERVER_SSH_PORT
#define GRIT_OPERATOR_SERVER_SSH_PORT "22"
#endif
#ifndef GRIT_OPERATOR_TARGET_BIND_HOST
#define GRIT_OPERATOR_TARGET_BIND_HOST "127.0.0.1"
#endif
#ifndef GRIT_OPERATOR_TARGET_DROPBEAR_PORT
#define GRIT_OPERATOR_TARGET_DROPBEAR_PORT "2222"
#endif
#ifndef GRIT_OPERATOR_KNOWN_HOSTS_POLICY
#define GRIT_OPERATOR_KNOWN_HOSTS_POLICY "off"
#endif
#ifndef GRIT_OPERATOR_FILE_SERVICE_ENABLE
#define GRIT_OPERATOR_FILE_SERVICE_ENABLE "no"
#endif
#ifndef GRIT_OPERATOR_FILE_SERVICE_PORT
#define GRIT_OPERATOR_FILE_SERVICE_PORT "22204"
#endif
#ifndef GRIT_OPERATOR_FILE_SERVICE_TLS
#define GRIT_OPERATOR_FILE_SERVICE_TLS "yes"
#endif
#ifndef GRIT_COMMAND_QUEUE_ENABLE
#define GRIT_COMMAND_QUEUE_ENABLE "no"
#endif
#ifndef GRIT_COMMAND_QUEUE_PORT
#define GRIT_COMMAND_QUEUE_PORT "22205"
#endif
#ifndef GRIT_COMMAND_QUEUE_TLS
#define GRIT_COMMAND_QUEUE_TLS "yes"
#endif
#ifndef GRIT_COMMAND_QUEUE_REQUIRE_TOKEN
#define GRIT_COMMAND_QUEUE_REQUIRE_TOKEN "yes"
#endif
#ifndef GRIT_COMMAND_QUEUE_TOKEN_SOURCE
#define GRIT_COMMAND_QUEUE_TOKEN_SOURCE "manual"
#endif
#ifndef GRIT_COMMAND_QUEUE_TOKEN
#define GRIT_COMMAND_QUEUE_TOKEN ""
#endif
#ifndef GRIT_COMMAND_QUEUE_ALLOWED_COMMANDS
#define GRIT_COMMAND_QUEUE_ALLOWED_COMMANDS "none"
#endif
#ifndef GRIT_COMMAND_QUEUE_EXECUTION
#define GRIT_COMMAND_QUEUE_EXECUTION "metadata-only"
#endif
#ifndef GRIT_COMMAND_QUEUE_ALLOW_ARBITRARY
#define GRIT_COMMAND_QUEUE_ALLOW_ARBITRARY "no"
#endif
#ifndef GRIT_COMMAND_QUEUE_POLL_INTERVAL_SEC
#define GRIT_COMMAND_QUEUE_POLL_INTERVAL_SEC "5"
#endif
#ifndef GRIT_COMMAND_QUEUE_POLL_JITTER_PCT
#define GRIT_COMMAND_QUEUE_POLL_JITTER_PCT "0"
#endif
#ifndef GRIT_COMMAND_QUEUE_POLL_BACKOFF
#define GRIT_COMMAND_QUEUE_POLL_BACKOFF "none"
#endif
#ifndef GRIT_COMMAND_QUEUE_POLL_MAX_INTERVAL_SEC
#define GRIT_COMMAND_QUEUE_POLL_MAX_INTERVAL_SEC "300"
#endif
#ifndef GRIT_COMMAND_QUEUE_MAX_POLLS
#define GRIT_COMMAND_QUEUE_MAX_POLLS "0"
#endif

/*
 * Effective runtime configuration follows the documented precedence in
 * runtime_config.c: compiled defaults, valid trailer overrides, environment
 * overrides, then applet-registered CLI overrides.
 */
#undef GRIT_RUNTIME_MODE
#undef GRIT_NORESIDUE_LEVEL
#undef GRIT_RUNTIME_ROOT
#undef GRIT_RUNTIME_ALLOW_FALLBACK_ROOT
#undef GRIT_RUNTIME_FALLBACK_ROOT
#undef GRIT_ZERO_ARG_MODE
#undef GRIT_ZERO_ARG_LOG_MODE
#undef GRIT_ZERO_ARG_CUSTOM_COMMAND
#undef GRIT_RSHELL_TRANSPORT
#undef GRIT_RSHELL_ENCRYPTION
#undef GRIT_RSHELL_ALLOW_PLAINTEXT
#undef GRIT_RSHELL_AUTHKEYS_MODE
#undef GRIT_RSHELL_RUN_MODE
#undef GRIT_RSHELL_SESSION_POLICY
#undef GRIT_RSHELL_GENERATE_HOSTKEY_IF_MISSING
#undef GRIT_RSHELL_SOCAT_PORT
#undef GRIT_RSHELL_SHELL_PROVIDER
#undef GRIT_RSHELL_CUSTOM_SHELL
#undef GRIT_RSHELL_RETRY_COUNT
#undef GRIT_RSHELL_RETRY_INTERVAL_SEC
#undef GRIT_RSHELL_RETRY_JITTER_PCT
#undef GRIT_RSHELL_RETRY_BACKOFF
#undef GRIT_RSHELL_RETRY_MAX_INTERVAL_SEC
#undef GRIT_AUTORUN_GUARD_ENABLE
#undef GRIT_AUTORUN_GUARD_PATH
#undef GRIT_AUTORUN_REENTRY_ACTION
#undef GRIT_AUTORUN_STALE_LOCK_POLICY
#undef GRIT_OPERATOR_REMOTE_FORWARD_PORT
#undef GRIT_OPERATOR_SERVER_HOST
#undef GRIT_OPERATOR_SERVER_USER
#undef GRIT_OPERATOR_SERVER_SSH_PORT
#undef GRIT_OPERATOR_TARGET_BIND_HOST
#undef GRIT_OPERATOR_TARGET_DROPBEAR_PORT
#undef GRIT_OPERATOR_KNOWN_HOSTS_POLICY
#undef GRIT_OPERATOR_FILE_SERVICE_ENABLE
#undef GRIT_OPERATOR_FILE_SERVICE_PORT
#undef GRIT_OPERATOR_FILE_SERVICE_TLS
#undef GRIT_COMMAND_QUEUE_ENABLE
#undef GRIT_COMMAND_QUEUE_PORT
#undef GRIT_COMMAND_QUEUE_TLS
#undef GRIT_COMMAND_QUEUE_REQUIRE_TOKEN
#undef GRIT_COMMAND_QUEUE_TOKEN_SOURCE
#undef GRIT_COMMAND_QUEUE_TOKEN
#undef GRIT_COMMAND_QUEUE_ALLOWED_COMMANDS
#undef GRIT_COMMAND_QUEUE_EXECUTION
#undef GRIT_COMMAND_QUEUE_ALLOW_ARBITRARY
#undef GRIT_COMMAND_QUEUE_POLL_INTERVAL_SEC
#undef GRIT_COMMAND_QUEUE_POLL_JITTER_PCT
#undef GRIT_COMMAND_QUEUE_POLL_BACKOFF
#undef GRIT_COMMAND_QUEUE_POLL_MAX_INTERVAL_SEC
#undef GRIT_COMMAND_QUEUE_MAX_POLLS
#define GRIT_RUNTIME_MODE bb_config_get("GRIT_RUNTIME_MODE")
#define GRIT_NORESIDUE_LEVEL bb_config_get("GRIT_NORESIDUE_LEVEL")
#define GRIT_RUNTIME_ROOT bb_config_get("GRIT_RUNTIME_ROOT")
#define GRIT_RUNTIME_ALLOW_FALLBACK_ROOT bb_config_get("GRIT_RUNTIME_ALLOW_FALLBACK_ROOT")
#define GRIT_RUNTIME_FALLBACK_ROOT bb_config_get("GRIT_RUNTIME_FALLBACK_ROOT")
#define GRIT_ZERO_ARG_MODE bb_config_get("GRIT_ZERO_ARG_MODE")
#define GRIT_ZERO_ARG_LOG_MODE bb_config_get("GRIT_ZERO_ARG_LOG_MODE")
#define GRIT_ZERO_ARG_CUSTOM_COMMAND bb_config_get("GRIT_ZERO_ARG_CUSTOM_COMMAND")
#define GRIT_RSHELL_TRANSPORT bb_config_get("GRIT_RSHELL_TRANSPORT")
#define GRIT_RSHELL_ENCRYPTION bb_config_get("GRIT_RSHELL_ENCRYPTION")
#define GRIT_RSHELL_ALLOW_PLAINTEXT bb_config_get("GRIT_RSHELL_ALLOW_PLAINTEXT")
#define GRIT_RSHELL_AUTHKEYS_MODE bb_config_get("GRIT_RSHELL_AUTHKEYS_MODE")
#define GRIT_RSHELL_RUN_MODE bb_config_get("GRIT_RSHELL_RUN_MODE")
#define GRIT_RSHELL_SESSION_POLICY bb_config_get("GRIT_RSHELL_SESSION_POLICY")
#define GRIT_RSHELL_GENERATE_HOSTKEY_IF_MISSING bb_config_get("GRIT_RSHELL_GENERATE_HOSTKEY_IF_MISSING")
#define GRIT_RSHELL_SOCAT_PORT bb_config_get("GRIT_RSHELL_SOCAT_PORT")
#define GRIT_RSHELL_SHELL_PROVIDER bb_config_get("GRIT_RSHELL_SHELL_PROVIDER")
#define GRIT_RSHELL_CUSTOM_SHELL bb_config_get("GRIT_RSHELL_CUSTOM_SHELL")
#define GRIT_RSHELL_RETRY_COUNT bb_config_get("GRIT_RSHELL_RETRY_COUNT")
#define GRIT_RSHELL_RETRY_INTERVAL_SEC bb_config_get("GRIT_RSHELL_RETRY_INTERVAL_SEC")
#define GRIT_RSHELL_RETRY_JITTER_PCT bb_config_get("GRIT_RSHELL_RETRY_JITTER_PCT")
#define GRIT_RSHELL_RETRY_BACKOFF bb_config_get("GRIT_RSHELL_RETRY_BACKOFF")
#define GRIT_RSHELL_RETRY_MAX_INTERVAL_SEC bb_config_get("GRIT_RSHELL_RETRY_MAX_INTERVAL_SEC")
#define GRIT_AUTORUN_GUARD_ENABLE bb_config_get("GRIT_AUTORUN_GUARD_ENABLE")
#define GRIT_AUTORUN_GUARD_PATH bb_config_get("GRIT_AUTORUN_GUARD_PATH")
#define GRIT_AUTORUN_REENTRY_ACTION bb_config_get("GRIT_AUTORUN_REENTRY_ACTION")
#define GRIT_AUTORUN_STALE_LOCK_POLICY bb_config_get("GRIT_AUTORUN_STALE_LOCK_POLICY")
#define GRIT_OPERATOR_REMOTE_FORWARD_PORT bb_config_get("GRIT_OPERATOR_REMOTE_FORWARD_PORT")
#define GRIT_OPERATOR_SERVER_HOST bb_config_get("GRIT_OPERATOR_SERVER_HOST")
#define GRIT_OPERATOR_SERVER_USER bb_config_get("GRIT_OPERATOR_SERVER_USER")
#define GRIT_OPERATOR_SERVER_SSH_PORT bb_config_get("GRIT_OPERATOR_SERVER_SSH_PORT")
#define GRIT_OPERATOR_TARGET_BIND_HOST bb_config_get("GRIT_OPERATOR_TARGET_BIND_HOST")
#define GRIT_OPERATOR_TARGET_DROPBEAR_PORT bb_config_get("GRIT_OPERATOR_TARGET_DROPBEAR_PORT")
#define GRIT_OPERATOR_KNOWN_HOSTS_POLICY bb_config_get("GRIT_OPERATOR_KNOWN_HOSTS_POLICY")
#define GRIT_OPERATOR_FILE_SERVICE_ENABLE bb_config_get("GRIT_OPERATOR_FILE_SERVICE_ENABLE")
#define GRIT_OPERATOR_FILE_SERVICE_PORT bb_config_get("GRIT_OPERATOR_FILE_SERVICE_PORT")
#define GRIT_OPERATOR_FILE_SERVICE_TLS bb_config_get("GRIT_OPERATOR_FILE_SERVICE_TLS")
#define GRIT_COMMAND_QUEUE_ENABLE bb_config_get("GRIT_COMMAND_QUEUE_ENABLE")
#define GRIT_COMMAND_QUEUE_PORT bb_config_get("GRIT_COMMAND_QUEUE_PORT")
#define GRIT_COMMAND_QUEUE_TLS bb_config_get("GRIT_COMMAND_QUEUE_TLS")
#define GRIT_COMMAND_QUEUE_REQUIRE_TOKEN bb_config_get("GRIT_COMMAND_QUEUE_REQUIRE_TOKEN")
#define GRIT_COMMAND_QUEUE_TOKEN_SOURCE bb_config_get("GRIT_COMMAND_QUEUE_TOKEN_SOURCE")
#define GRIT_COMMAND_QUEUE_TOKEN bb_config_get("GRIT_COMMAND_QUEUE_TOKEN")
#define GRIT_COMMAND_QUEUE_ALLOWED_COMMANDS bb_config_get("GRIT_COMMAND_QUEUE_ALLOWED_COMMANDS")
#define GRIT_COMMAND_QUEUE_EXECUTION bb_config_get("GRIT_COMMAND_QUEUE_EXECUTION")
#define GRIT_COMMAND_QUEUE_ALLOW_ARBITRARY bb_config_get("GRIT_COMMAND_QUEUE_ALLOW_ARBITRARY")
#define GRIT_COMMAND_QUEUE_POLL_INTERVAL_SEC bb_config_get("GRIT_COMMAND_QUEUE_POLL_INTERVAL_SEC")
#define GRIT_COMMAND_QUEUE_POLL_JITTER_PCT bb_config_get("GRIT_COMMAND_QUEUE_POLL_JITTER_PCT")
#define GRIT_COMMAND_QUEUE_POLL_BACKOFF bb_config_get("GRIT_COMMAND_QUEUE_POLL_BACKOFF")
#define GRIT_COMMAND_QUEUE_POLL_MAX_INTERVAL_SEC bb_config_get("GRIT_COMMAND_QUEUE_POLL_MAX_INTERVAL_SEC")
#define GRIT_COMMAND_QUEUE_MAX_POLLS bb_config_get("GRIT_COMMAND_QUEUE_MAX_POLLS")

#endif
