#ifndef BUSIERBOX_EFFECTIVE_CONFIG_H
#define BUSIERBOX_EFFECTIVE_CONFIG_H

#include "runtime_config.h"

#ifndef BB_RUNTIME_MODE
#define BB_RUNTIME_MODE "extract"
#endif
#ifndef BB_RUNTIME_ROOT
#define BB_RUNTIME_ROOT "./.busierbox"
#endif
#ifndef BB_RUNTIME_ALLOW_FALLBACK_ROOT
#define BB_RUNTIME_ALLOW_FALLBACK_ROOT "no"
#endif
#ifndef BB_RUNTIME_FALLBACK_ROOT
#define BB_RUNTIME_FALLBACK_ROOT "/tmp/.busierbox"
#endif
#ifndef BB_ZERO_ARG_MODE
#define BB_ZERO_ARG_MODE "help"
#endif
#ifndef BB_ZERO_ARG_LOG_MODE
#define BB_ZERO_ARG_LOG_MODE "quiet"
#endif
#ifndef BB_ZERO_ARG_CUSTOM_COMMAND
#define BB_ZERO_ARG_CUSTOM_COMMAND ""
#endif
#ifndef BB_RSHELL_MODE
#define BB_RSHELL_MODE "ssh"
#endif
#ifndef BB_RSHELL_TRANSPORT
#define BB_RSHELL_TRANSPORT BB_RSHELL_MODE
#endif
#ifndef BB_RSHELL_ENCRYPTION
#define BB_RSHELL_ENCRYPTION "tls"
#endif
#ifndef BB_RSHELL_ALLOW_PLAINTEXT
#define BB_RSHELL_ALLOW_PLAINTEXT "no"
#endif
#ifndef BB_RSHELL_AUTHKEYS_MODE
#define BB_RSHELL_AUTHKEYS_MODE "disabled"
#endif
#ifndef BB_RSHELL_RUN_MODE
#define BB_RSHELL_RUN_MODE "auto"
#endif
#ifndef BB_RSHELL_GENERATE_HOSTKEY_IF_MISSING
#define BB_RSHELL_GENERATE_HOSTKEY_IF_MISSING "no"
#endif
#ifndef BB_RSHELL_SOCAT_PORT
#define BB_RSHELL_SOCAT_PORT "22203"
#endif
#ifndef BB_RSHELL_SHELL_PROVIDER
#define BB_RSHELL_SHELL_PROVIDER "auto"
#endif
#ifndef BB_RSHELL_CUSTOM_SHELL
#define BB_RSHELL_CUSTOM_SHELL ""
#endif
#ifndef BB_RSHELL_RETRY_COUNT
#define BB_RSHELL_RETRY_COUNT "1"
#endif
#ifndef BB_RSHELL_RETRY_INTERVAL_SEC
#define BB_RSHELL_RETRY_INTERVAL_SEC "5"
#endif
#ifndef BB_RSHELL_RETRY_JITTER_PCT
#define BB_RSHELL_RETRY_JITTER_PCT "20"
#endif
#ifndef BB_RSHELL_RETRY_BACKOFF
#define BB_RSHELL_RETRY_BACKOFF "none"
#endif
#ifndef BB_RSHELL_RETRY_MAX_INTERVAL_SEC
#define BB_RSHELL_RETRY_MAX_INTERVAL_SEC "300"
#endif
#ifndef BB_AUTORUN_GUARD_ENABLE
#define BB_AUTORUN_GUARD_ENABLE "yes"
#endif
#ifndef BB_AUTORUN_GUARD_PATH
#define BB_AUTORUN_GUARD_PATH BB_RUNTIME_ROOT "/run"
#endif
#ifndef BB_AUTORUN_REENTRY_ACTION
#define BB_AUTORUN_REENTRY_ACTION "status"
#endif
#ifndef BB_AUTORUN_STALE_LOCK_POLICY
#define BB_AUTORUN_STALE_LOCK_POLICY "recover"
#endif
#ifndef BB_OPERATOR_REMOTE_FORWARD_PORT
#define BB_OPERATOR_REMOTE_FORWARD_PORT "2200"
#endif
#ifndef BB_OPERATOR_SERVER_HOST
#define BB_OPERATOR_SERVER_HOST ""
#endif
#ifndef BB_OPERATOR_SERVER_USER
#define BB_OPERATOR_SERVER_USER "operator"
#endif
#ifndef BB_OPERATOR_SERVER_SSH_PORT
#define BB_OPERATOR_SERVER_SSH_PORT "22"
#endif
#ifndef BB_OPERATOR_TARGET_BIND_HOST
#define BB_OPERATOR_TARGET_BIND_HOST "127.0.0.1"
#endif
#ifndef BB_OPERATOR_TARGET_DROPBEAR_PORT
#define BB_OPERATOR_TARGET_DROPBEAR_PORT "2222"
#endif
#ifndef BB_OPERATOR_KNOWN_HOSTS_POLICY
#define BB_OPERATOR_KNOWN_HOSTS_POLICY "off"
#endif
#ifndef BB_OPERATOR_FILE_SERVICE_ENABLE
#define BB_OPERATOR_FILE_SERVICE_ENABLE "no"
#endif
#ifndef BB_OPERATOR_FILE_SERVICE_PORT
#define BB_OPERATOR_FILE_SERVICE_PORT "22204"
#endif
#ifndef BB_OPERATOR_FILE_SERVICE_TLS
#define BB_OPERATOR_FILE_SERVICE_TLS "yes"
#endif

/*
 * Effective runtime configuration follows the documented precedence in
 * runtime_config.c: compiled defaults, valid trailer overrides, environment
 * overrides, then applet-registered CLI overrides.
 */
#undef BB_RUNTIME_MODE
#undef BB_RUNTIME_ROOT
#undef BB_RUNTIME_ALLOW_FALLBACK_ROOT
#undef BB_RUNTIME_FALLBACK_ROOT
#undef BB_ZERO_ARG_MODE
#undef BB_ZERO_ARG_LOG_MODE
#undef BB_ZERO_ARG_CUSTOM_COMMAND
#undef BB_RSHELL_TRANSPORT
#undef BB_RSHELL_ENCRYPTION
#undef BB_RSHELL_ALLOW_PLAINTEXT
#undef BB_RSHELL_AUTHKEYS_MODE
#undef BB_RSHELL_RUN_MODE
#undef BB_RSHELL_GENERATE_HOSTKEY_IF_MISSING
#undef BB_RSHELL_SOCAT_PORT
#undef BB_RSHELL_SHELL_PROVIDER
#undef BB_RSHELL_CUSTOM_SHELL
#undef BB_RSHELL_RETRY_COUNT
#undef BB_RSHELL_RETRY_INTERVAL_SEC
#undef BB_RSHELL_RETRY_JITTER_PCT
#undef BB_RSHELL_RETRY_BACKOFF
#undef BB_RSHELL_RETRY_MAX_INTERVAL_SEC
#undef BB_AUTORUN_GUARD_ENABLE
#undef BB_AUTORUN_GUARD_PATH
#undef BB_AUTORUN_REENTRY_ACTION
#undef BB_AUTORUN_STALE_LOCK_POLICY
#undef BB_OPERATOR_REMOTE_FORWARD_PORT
#undef BB_OPERATOR_SERVER_HOST
#undef BB_OPERATOR_SERVER_USER
#undef BB_OPERATOR_SERVER_SSH_PORT
#undef BB_OPERATOR_TARGET_BIND_HOST
#undef BB_OPERATOR_TARGET_DROPBEAR_PORT
#undef BB_OPERATOR_KNOWN_HOSTS_POLICY
#undef BB_OPERATOR_FILE_SERVICE_ENABLE
#undef BB_OPERATOR_FILE_SERVICE_PORT
#undef BB_OPERATOR_FILE_SERVICE_TLS
#define BB_RUNTIME_MODE bb_config_get("BB_RUNTIME_MODE")
#define BB_RUNTIME_ROOT bb_config_get("BB_RUNTIME_ROOT")
#define BB_RUNTIME_ALLOW_FALLBACK_ROOT bb_config_get("BB_RUNTIME_ALLOW_FALLBACK_ROOT")
#define BB_RUNTIME_FALLBACK_ROOT bb_config_get("BB_RUNTIME_FALLBACK_ROOT")
#define BB_ZERO_ARG_MODE bb_config_get("BB_ZERO_ARG_MODE")
#define BB_ZERO_ARG_LOG_MODE bb_config_get("BB_ZERO_ARG_LOG_MODE")
#define BB_ZERO_ARG_CUSTOM_COMMAND bb_config_get("BB_ZERO_ARG_CUSTOM_COMMAND")
#define BB_RSHELL_TRANSPORT bb_config_get("BB_RSHELL_TRANSPORT")
#define BB_RSHELL_ENCRYPTION bb_config_get("BB_RSHELL_ENCRYPTION")
#define BB_RSHELL_ALLOW_PLAINTEXT bb_config_get("BB_RSHELL_ALLOW_PLAINTEXT")
#define BB_RSHELL_AUTHKEYS_MODE bb_config_get("BB_RSHELL_AUTHKEYS_MODE")
#define BB_RSHELL_RUN_MODE bb_config_get("BB_RSHELL_RUN_MODE")
#define BB_RSHELL_GENERATE_HOSTKEY_IF_MISSING bb_config_get("BB_RSHELL_GENERATE_HOSTKEY_IF_MISSING")
#define BB_RSHELL_SOCAT_PORT bb_config_get("BB_RSHELL_SOCAT_PORT")
#define BB_RSHELL_SHELL_PROVIDER bb_config_get("BB_RSHELL_SHELL_PROVIDER")
#define BB_RSHELL_CUSTOM_SHELL bb_config_get("BB_RSHELL_CUSTOM_SHELL")
#define BB_RSHELL_RETRY_COUNT bb_config_get("BB_RSHELL_RETRY_COUNT")
#define BB_RSHELL_RETRY_INTERVAL_SEC bb_config_get("BB_RSHELL_RETRY_INTERVAL_SEC")
#define BB_RSHELL_RETRY_JITTER_PCT bb_config_get("BB_RSHELL_RETRY_JITTER_PCT")
#define BB_RSHELL_RETRY_BACKOFF bb_config_get("BB_RSHELL_RETRY_BACKOFF")
#define BB_RSHELL_RETRY_MAX_INTERVAL_SEC bb_config_get("BB_RSHELL_RETRY_MAX_INTERVAL_SEC")
#define BB_AUTORUN_GUARD_ENABLE bb_config_get("BB_AUTORUN_GUARD_ENABLE")
#define BB_AUTORUN_GUARD_PATH bb_config_get("BB_AUTORUN_GUARD_PATH")
#define BB_AUTORUN_REENTRY_ACTION bb_config_get("BB_AUTORUN_REENTRY_ACTION")
#define BB_AUTORUN_STALE_LOCK_POLICY bb_config_get("BB_AUTORUN_STALE_LOCK_POLICY")
#define BB_OPERATOR_REMOTE_FORWARD_PORT bb_config_get("BB_OPERATOR_REMOTE_FORWARD_PORT")
#define BB_OPERATOR_SERVER_HOST bb_config_get("BB_OPERATOR_SERVER_HOST")
#define BB_OPERATOR_SERVER_USER bb_config_get("BB_OPERATOR_SERVER_USER")
#define BB_OPERATOR_SERVER_SSH_PORT bb_config_get("BB_OPERATOR_SERVER_SSH_PORT")
#define BB_OPERATOR_TARGET_BIND_HOST bb_config_get("BB_OPERATOR_TARGET_BIND_HOST")
#define BB_OPERATOR_TARGET_DROPBEAR_PORT bb_config_get("BB_OPERATOR_TARGET_DROPBEAR_PORT")
#define BB_OPERATOR_KNOWN_HOSTS_POLICY bb_config_get("BB_OPERATOR_KNOWN_HOSTS_POLICY")
#define BB_OPERATOR_FILE_SERVICE_ENABLE bb_config_get("BB_OPERATOR_FILE_SERVICE_ENABLE")
#define BB_OPERATOR_FILE_SERVICE_PORT bb_config_get("BB_OPERATOR_FILE_SERVICE_PORT")
#define BB_OPERATOR_FILE_SERVICE_TLS bb_config_get("BB_OPERATOR_FILE_SERVICE_TLS")

#endif
